name: Render
on:
  push:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Trigger Render deploy for web
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SRV_TOKEN }}
        api-key: ${{ secrets.API_KEY }}